### ISSUE TITLE
FAQ section - Questions and answers 

### ISSUE THREAD

**Issue by mahima98** [Front-End-Coders-Mauritius/frontendmu-astro#23]
I need the questions and answers for the FAQ page,
@MrSunshyne 

![faq](https://user-images.githubusercontent.com/45752743/214622187-ea2156e6-70d0-4806-b4ad-bf6f82871d57.png)

**Comment by MrSunshyne** [comment]
@mahima98 

The link in the first sentence should point towards our discord probably. with the text: 

Have a different question and can't find the answer you're looking for? **Reach out to our community on discord** and someone might be able to help you! 
The bold part is the link.

The faq should be only one column and contain accordions that allow collapse/uncollapse the sections. 
Look at this design example :

![image](https://user-images.githubusercontent.com/1721611/214926379-a3ccc087-38d2-493f-ba85-d2ba7fa3fa53.png)

As for the data, it's not ready yet, but it should not be hardcoded in the template. I think the new [Astro Content Collections](https://docs.astro.build/en/guides/content-collections/) might be very useful to get the data for the FAQ (instead of using json). You can use a json file for now if content collections seem complicated.

**Comment by mahima98** [comment]
New FAQ design updated and I used the astro content collections :D

Please review it here: 
https://github.com/Front-End-Coders-Mauritius/frontendmu-astro/commit/11a531c1e268104ea0aaf33336443ae4ba48b25c#diff-5a68723d34fc0927af8f004160bbc6c6e1d22d12f6f225745a1db5aba1f90114

![faq-content](https://user-images.githubusercontent.com/45752743/215326147-b02db371-f300-4b51-ab94-3f27f82f9354.png)

And lemme know if there's any other things to improve :D

**Comment by MrSunshyne** [comment]
Some comments

1. The **answer** field should not be in the frontmatter, but rather the content of the MD file. This allows using markdown in the answers section. Accordingly use **set:html** to render it in the astro file

2. Create a PR with the new branch..it's easier to review from a PR and vercel will automatically make a preview deployment for you

**Comment by mahima98** [comment]
@MrSunshyne :D
I changed the answer field from frontmatter to content in the MD file.
But am having an issue for the set:html, I think it doesn't actually render html 🤔

preview: https://frontendmu-astro-git-feature-faq-frontendmu.vercel.app/faq

**Comment by MrSunshyne** [comment]
[merged](https://github.com/Front-End-Coders-Mauritius/frontendmu-astro/pull/25) and exists on /faq, but not yet implemented in the main menu
